Repository com2027/API, pull requests merged in 2019-04, with the labels that each got.

#19 Friends routes
  app.js
  migrations/20190327123132-create-friends.js
  migrations/20190327191703-create-fugitive-stat.js
  models/bountyhunterstat.js
  models/friends.js
  models/fugitivestat.js
  models/user.js
  routes/friends.js
Labels: enhancement

#21 Stats routes completed
  app.js
  models/bountyhunterstat.js
  models/fugitivestat.js
  models/user.js
  routes/stats.js
Labels: enhancement

#22 Deployment of stats routes
  app.js
  models/bountyhunterstat.js
  models/fugitivestat.js
  models/user.js
  routes/stats.js
Labels: Deployment

#24 Added change password with current password route
  routes/users.js
Labels: enhancement

#23 Testing framework set up
  app.js
  package-lock.json
  package.json
  routes/friends.js
  routes/users.js
  test/user.test.js
Labels: enhancement

#25 Deploying the change password with current password endpoint of API
  routes/users.js
Labels: Deployment

#26 Fixed testing and added a few more tests
  .gitignore
  config/config.json
  package.json
  test/user.test.js
Labels: Testing

#27 Created registration and login tests for users
  package-lock.json
  routes/users.js
  test/data/users.js
  test/friend.test.js
  test/helpers/create-user.js
  test/user.test.js
Labels: Testing

#28 Fixed foreign key errors with friends and stats when deleting users
  .gitignore
  migrations/20190327123132-create-friends.js
  migrations/20190327191703-create-fugitive-stat.js
  migrations/20190327193712-create-bounty-hunter-stat.js
  models/bountyhunterstat.js
  models/friends.js
  models/fugitivestat.js
  routes/users.js
Labels: bug

#29 Deploying foreign key bug fix
  .gitignore
  migrations/20190327123132-create-friends.js
  migrations/20190327191703-create-fugitive-stat.js
  migrations/20190327193712-create-bounty-hunter-stat.js
  models/bountyhunterstat.js
  models/friends.js
  models/fugitivestat.js
  routes/users.js
Labels: Deployment

#30 Fixed the errors we were getting with test
  package-lock.json
  package.json
  test/data/users.js
  test/helpers/create-user.js
  test/user.test.js
Labels: Testing

#31 Added more helper functions, test data and example tests
  package-lock.json
  package.json
  test/bountyhunterstats.test.js
  test/data/stats.js
  test/friend.test.js
  test/fugitivestats.test.js
  test/helpers/create-friends.js
  test/helpers/create-stat.js
  test/helpers/login-user.js
  test/user.test.js
Labels: Testing
